CREATE TABLE [UploadedFiles](
	[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[FileName] NVARCHAR(512) NOT NULL,
	[FilePath] NVARCHAR(1024) NOT NULL,
	[InsertDate] DATETIME NULL DEFAULT(GETDATE())
)
GO